export class Player {
    public id;
    constructor(public nom: string, public prenom: string,
        public dateNaissance: string, public lieuNaissance: string,
        public nationalite: string, public adresse: string, public poste: string,
        public capitaine: string, public numero: string, public maillot: string,
        public certificatMedicale: string, public clubPrecedent: string,
        public clubDepuis: string, public parcScol: string, public deuxiemePoste: string,
        public pied: string, public numLicence: string, public pointure: string,
        public short: string, public licence: string, public parcSport: string,
        public email: string, public mobile: string, public fix: string,
        public allergie: string, public hospitalization: string, public contreIndication: string,
        public cni: string, public passport: string, public cni_expiration: string,
        public passport_expiration: string, public password: string,
        public club: string, public type: string, public match_risk: number,
        public qualification: string, public adresse_etrange: string,
        public pere: string, public fonction_pere: string, public mere: string,
        public mere_fonction: string, public contact_urgence: string,
        public contact_urgence_tele: string, public nomber_freres: string,
        public country_pere: string, public country_mere: string,
        public country: string, public passport1: string,
        public passport_two: string, public date1: string,
        public passport_expiration_two: string,
        public date_debut_pret: string,
        public date_return_pret: string,
        public salaire_pret: number,
        public club_pret: string,
        public status: string,
        public instat_name: string,
        public gps_type: string,
        public gps_id: string,
        public preparateur: string,
        public tel_preparateur: string,
        public email_preparateur: string,
        // public nationalite_id:number|null = null ,
        public nationalite_ids: number[] = [],
        public lang: string = "fr",
        public club_id: number | null = null,
        public info: string = "",
        public freres: any[] = [],
    ) { }

}
